rootProject.name = 'sure-partner-observability'

include 'sure-partner-observability-core'
include 'sure-partner-observability-spring-boot-autoconfigure'
include 'sure-partner-observability-spring-boot-starter'
include 'sure-partner-observability-test-app'
include 'sure-partner-observability-reactive-test-app'
include 'sure-partner-observability-local-test-support'
