events {}

http {
  access_log off;
  server_tokens off;
  server {
    listen 8080;
    location = /actuator/prometheus {
      default_type text/plain;
      alias /usr/share/nginx/html/local-metrics.prom;
    }
  }
}
