package com.samsung.sure.partner.observability.core.model;

public enum TimelineStage {
    ASYNC_REQUEST_SENT,
    ASYNC_ACK_RECEIVED,
    ASYNC_ACK_NOT_RECEIVED,
    CALLBACK_RECEIVED,
    CALLBACK_RETRY_RECEIVED,
    CALLBACK_AUTHENTICATED,
    CALLBACK_VALIDATED,
    CALLBACK_PROCESSING_STARTED,
    CALLBACK_PROCESSED,
    CALLBACK_PROCESSING_FAILED,
    CALLBACK_RESPONSE_SENT,
    CALLBACK_RESPONSE_WRITE_FAILED
}
